[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py38"

[tool.ruff.format]
quote-style = "double"

[tool.ruff.lint]
select = ["F", "I", "N", "W", "E"]
ignore = ["N814", "N812", "N806"]
